export const mockShopInfo = {
  name: "AADAGAM JEWELLERY",
  tagline: "Timeless Elegance, Handcrafted Perfection",
  subTagline: "Crafting exquisite gold, diamond, & antique polki treasures since 1988",
  logoUrl: "https://images.unsplash.com/photo-1605100804763-247f67b3557e?auto=format&fit=crop&w=200&q=80",
  address: "104 Royal Heritage Plaza, MG Road, Jewellery Quarter, Mumbai, Maharashtra 400001",
  mapDirectionsUrl: "https://maps.google.com/?q=Mumbai+Jewellery+Quarter",
  phonePrimary: "+91 98765 43210",
  phoneSecondary: "+91 98765 43211",
  email: "contact@aadagamjewellery.com",
  whatsapp: "919876543210",
  announcement: "100% BIS Hallmarked 22K Gold & Certified Solitaire Diamonds",
  socials: {
    facebook: "https://facebook.com/aadagamjewellery",
    instagram: "https://instagram.com/aadagamjewellery",
    youtube: "https://youtube.com/@aadagamjewellery",
  },
};

export const mockSlides = [
  {
    id: 1,
    title: "The Royal Bridal Heritage Collection",
    subtitle: "Ornate 22K Kundan & Polki Necklaces Crafted for Unforgettable Weddings",
    desktopImg: "https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?auto=format&fit=crop&w=1920&h=700&q=80",
    mobileImg: "https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?auto=format&fit=crop&w=1024&h=600&q=80",
    ctaText: "Explore Bridal Collection",
    ctaLink: "#gallery",
  },
  {
    id: 2,
    title: "Handcrafted 24K Gold Masterpieces",
    subtitle: "Pure Gold Artistry Passed Down Through Generations of Master Goldsmiths",
    desktopImg: "https://images.unsplash.com/photo-1601121141461-9d6647bca1ed?auto=format&fit=crop&w=1920&h=700&q=80",
    mobileImg: "https://images.unsplash.com/photo-1601121141461-9d6647bca1ed?auto=format&fit=crop&w=1024&h=600&q=80",
    ctaText: "View Gold Jewellery",
    ctaLink: "#gallery",
  },
  {
    id: 3,
    title: "Solitaire & Certified Diamond Jewels",
    subtitle: "Brilliant Cuts & Timeless Designs for Your Special Moments",
    desktopImg: "https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?auto=format&fit=crop&w=1920&h=700&q=80",
    mobileImg: "https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?auto=format&fit=crop&w=1024&h=600&q=80",
    ctaText: "Discover Diamonds",
    ctaLink: "#gallery",
  },
  {
    id: 4,
    title: "Temple & Antique Gold Chokers",
    subtitle: "Sacred Motifs and Intricate Nakshi Work Infused with Modern Elegance",
    desktopImg: "https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?auto=format&fit=crop&w=1920&h=700&q=80",
    mobileImg: "https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?auto=format&fit=crop&w=1024&h=600&q=80",
    ctaText: "Browse Temple Jewels",
    ctaLink: "#gallery",
  },
  {
    id: 5,
    title: "Contemporary Everyday Luxury",
    subtitle: "Lightweight Gold & Diamond Essentials for the Modern Connoisseur",
    desktopImg: "https://images.unsplash.com/photo-1611591475179-42f338829141?auto=format&fit=crop&w=1920&h=700&q=80",
    mobileImg: "https://images.unsplash.com/photo-1611591475179-42f338829141?auto=format&fit=crop&w=1024&h=600&q=80",
    ctaText: "Shop Daily Wear",
    ctaLink: "#gallery",
  },
];

export const mockCategories = ["All", "Necklaces", "Earrings", "Bangles", "Rings", "Bridal Sets"];

export const mockGalleryImages = [
  {
    id: "g1",
    title: "Maharani Uncut Polki & Emerald Haar",
    category: "Bridal Sets",
    purity: "22K Gold & Natural Emeralds",
    imageUrl: "https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?auto=format&fit=crop&w=1000&q=80",
    description: "Extravagant bridal layered necklace encrusted with uncut syndicate polki diamonds and vibrant Zambian emerald drops.",
    code: "AG-BR-901",
  },
  {
    id: "g2",
    title: "Royal Temple Nakshi Gold Choker",
    category: "Necklaces",
    purity: "22K Pure Gold (BIS Hallmarked)",
    imageUrl: "https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?auto=format&fit=crop&w=1000&q=80",
    description: "Traditional South Indian temple choker featuring divine Goddess Lakshmi motifs and handcrafted ruby hangings.",
    code: "AG-NK-402",
  },
  {
    id: "g3",
    title: "Celestial Solitaire Diamond Drop Earrings",
    category: "Earrings",
    purity: "18K White Gold & VVS Diamonds",
    imageUrl: "https://images.unsplash.com/photo-1630019852942-f89202989a59?auto=format&fit=crop&w=1000&q=80",
    description: "Cascading solitaire diamond earrings with brilliant pear-cut drops, certified by IGI for exceptional clarity.",
    code: "AG-ER-108",
  },
  {
    id: "g4",
    title: "Handcrafted Antique Kada Bangles",
    category: "Bangles",
    purity: "22K Antique Gold",
    imageUrl: "https://images.unsplash.com/photo-1611591475179-42f338829141?auto=format&fit=crop&w=1000&q=80",
    description: "Pair of thick antique gold kadas detailed with hand-carved floral patterns and screw closure.",
    code: "AG-BG-305",
  },
  {
    id: "g5",
    title: "Majestic Marquise Diamond Halo Ring",
    category: "Rings",
    purity: "18K Rose Gold & Diamonds",
    imageUrl: "https://images.unsplash.com/photo-1605100804763-247f67b3557e?auto=format&fit=crop&w=1000&q=80",
    description: "Stunning 2-carat marquise cut diamond ring surrounded by a delicate double halo of round brilliant diamonds.",
    code: "AG-RN-512",
  },
  {
    id: "g6",
    title: "Nizam Heritage Chandelier Jhumkas",
    category: "Earrings",
    purity: "22K Yellow Gold & Pearl Drops",
    imageUrl: "https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?auto=format&fit=crop&w=1000&q=80",
    description: "Ornate multi-tier gold jhumkas adorned with freshwater pearls and intricate enameling (Meenakari).",
    code: "AG-ER-214",
  },
  {
    id: "g7",
    title: "Vedic Royal Kundan & Ruby Bridal Ensemble",
    category: "Bridal Sets",
    purity: "22K Gold, Polki & Rubies",
    imageUrl: "https://images.unsplash.com/photo-1601121141461-9d6647bca1ed?auto=format&fit=crop&w=1000&q=80",
    description: "Comprehensive bridal set including heavy choker, long rani haar, matching earrings, and maang tikka.",
    code: "AG-BR-990",
  },
  {
    id: "g8",
    title: "Minimalist Diamond Tennis Bracelet",
    category: "Bangles",
    purity: "18K Yellow Gold & Diamonds",
    imageUrl: "https://images.unsplash.com/photo-1599643477877-530eb83abc8e?auto=format&fit=crop&w=1000&q=80",
    description: "Classic continuous line of prong-set brilliant round diamonds crafted in rich 18K yellow gold.",
    code: "AG-BG-411",
  },
  {
    id: "g9",
    title: "Vintage Floral Ruby & Diamond Pendant",
    category: "Necklaces",
    purity: "18K Gold & Burmese Rubies",
    imageUrl: "https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?auto=format&fit=crop&w=1000&q=80",
    description: "Art deco inspired floral pendant featuring pigeon-blood Burmese rubies and pave diamond petals.",
    code: "AG-NK-330",
  },
  {
    id: "g10",
    title: "Crown Solitaire Engagement Ring",
    category: "Rings",
    purity: "Platinum 950 & Solitaire",
    imageUrl: "https://images.unsplash.com/photo-1605100804763-247f67b3557e?auto=format&fit=crop&w=1000&q=80",
    description: "Timeless 6-prong platinum crown setting carrying a flawless 1.5ct GIA-certified solitaire diamond.",
    code: "AG-RN-601",
  },
  {
    id: "g11",
    title: "Filigree Mesh Gold Broad Bangle",
    category: "Bangles",
    purity: "22K Yellow Gold",
    imageUrl: "https://images.unsplash.com/photo-1611591475179-42f338829141?auto=format&fit=crop&w=1000&q=80",
    description: "Lightweight flexible mesh bangle with diamond-cut pattern for unmatched luster and everyday elegance.",
    code: "AG-BG-209",
  },
  {
    id: "g12",
    title: "Contemporary Diamond Hoop Earrings",
    category: "Earrings",
    purity: "18K Rose Gold",
    imageUrl: "https://images.unsplash.com/photo-1630019852942-f89202989a59?auto=format&fit=crop&w=1000&q=80",
    description: "Inside-out diamond hoop earrings engineered for comfortable wear and maximum light brilliance.",
    code: "AG-ER-340",
  },
];

export const mockVideos = [
  {
    id: "v1",
    title: "Inside Our Atelier: The Art of Kundan & Polki Jewellery",
    youtubeId: "dQw4w9WgXcQ",
    thumbnail: "https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?auto=format&fit=crop&w=800&q=80",
    category: "Craftsmanship",
    duration: "3:45",
    description: "Witness how our master craftsmen transform raw gold and uncut diamonds into heirloom-quality treasures.",
  },
  {
    id: "v2",
    title: "Aadagam Bridal Campaign 2026 | Royal Reflections",
    youtubeId: "LXb3EKWsInQ",
    thumbnail: "https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?auto=format&fit=crop&w=800&q=80",
    category: "Bridal Showcase",
    duration: "2:15",
    description: "Explore our latest bridal collection designed to elevate the grace of every modern bride.",
  },
  {
    id: "v3",
    title: "Understanding Diamond Purity: 4Cs Guide by Aadagam",
    youtubeId: "J---aiyznGQ",
    thumbnail: "https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?auto=format&fit=crop&w=800&q=80",
    category: "Jewellery Guide",
    duration: "5:10",
    description: "Our certified gemologist explains Cut, Color, Clarity, and Carat weight to help you make informed choices.",
  },
  {
    id: "v4",
    title: "Handcrafted Antique Gold Bangle Making Process",
    youtubeId: "fJ9rUzIMcDQ",
    thumbnail: "https://images.unsplash.com/photo-1611591475179-42f338829141?auto=format&fit=crop&w=800&q=80",
    category: "Behind The Scenes",
    duration: "4:00",
    description: "Step inside our workshop to see the precise hammering, engraving, and finishing of 24K gold bangles.",
  },
];

export const mockAboutContent = {
  title: "Our Heritage & Passion for Perfection",
  subtitle: "Blending Traditional Indian Artistry with Contemporary Refinement Since 1988",
  historyParagraphs: [
    "Founded in 1988 by master goldsmith Rajeshwar Aadagam, Aadagam Jewellery began as a humble boutique studio with a single vision: to create authentic, heirloom-quality gold and diamond jewellery that celebrates life's most precious milestones.",
    "Over three decades later, Aadagam Jewellery has grown into a trusted hallmark of purity and artistic excellence. Every piece in our showroom is meticulously designed, ethically sourced, and handcrafted by seasoned artisans whose skills have been refined over generations.",
    "Whether it is an ornate Kundan bridal ensemble, a timeless solitaire engagement ring, or lightweight daily wear, our commitment to 100% BIS hallmarked gold and certified diamonds remains unwavering.",
  ],
  founder: {
    name: "Rajeshwar Aadagam",
    role: "Founder & Master Craftsman",
    quote: "Jewellery is not merely an ornament; it is a sacred record of love, heritage, and emotion passed from one generation to the next.",
    image: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=600&q=80",
  },
  specialization: [
    "Certified 22K & 24K Handcrafted Gold Jewellery",
    "Uncut Syndicate Polki & Kundan Bridal Sets",
    "GIA & IGI Certified Solitaire Diamonds",
    "Temple Nakshi & Antique Heritage Collections",
    "Custom Bespoke Jewellery Design Service",
  ],
};
